### ISSUE TITLE
spark_read_bigquery reads dates, times and timestamps as microseconds from the Unix epoch

### ISSUE THREAD

**Issue by lambiase** [miraisolutions/sparkbq#5]
We should be able to read dates, times and timestamps as such, and not as numbers as it currently happens (microseconds from the Unix epoch).
This issue might be related to https://github.com/spotify/spark-bigquery/pull/35 and to https://avro.apache.org/docs/1.8.0/spec.html#Timestamp+%28microsecond+precision%29

**Comment by xeroquark** [comment]
As @lambiase pointed out, there seems to be a hacky (involving copying the whole avro-spark part) pull request waiting to be merged into Spotify' Spark-BigQuery. 

Currently, we lose precision due to this conversion and we cannot recover the actual time from an entry like '1.494650e+15'.

**Comment by xeroquark** [comment]
It looks like we are not losing any precision. So, for now using something like 
`as.POSIXct(val/10^6, origin="1970-01-01")`
would be enough to convert numbers to timestamps.

**Comment by martinstuder** [comment]
Re-opening as this is still an issue - we just have a workaround

**Comment by martinstuder** [comment]
Handling of data types depends on the import/export type being used (see https://github.com/miraisolutions/spark-bigquery). When using direct import, dates, times and timestamps are correctly determined as such.
